### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by FatBuck** [bcwood/dotMath#1]
I found a few things that might be bugs.  I tried to use all the operators and functions in the documentation and the following wouldn't evaluate for me:

the '=' operator (e.g. 1=1 throws an exception).  This is OK because '==' works as expected, so maybe just remove '=' from the documentation.

the '&' operator (e.g. 1&1 throws an exception).  This doesn't seem right.  I read some of the code and it looks like && and || are supported, but neither work.

Only constants work in the if statement true/false expressions.  (e.g. if(1<2,3,4) results in 3, but if(1<2,**2+1**,4) results in an exception.

Maybe these aren't bugs, but they seem to be.

**Comment by bcwood** [comment]
The '=' operator was just incorrect documentation from the original project, so I removed it (54f302578cd27bc0f0ebe46d25aaa2af0051d6a0).

Added support for && and || operators in 73a0062e2bb6b246f64ee4f7841fe4aae0b4a508 (it's correct that & throws an exception).

You can use an expression in an If statement if you surround it in parentheses (e.g., If (1<2,(2+1),4). Added test cases in 1f82d2e9b0ecda0ced3c2fcc606545e7f944e8ac to cover this scenario. At some point I may look into making this case work without the parentheses.
